openapi: 3.0.0
info:
  title: PS5 STORE
  description: SPANISH PRODUCTS API DOCUMENTATION 
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Desarrollo
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron devueltos de forma exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error del servidor. Usualmente generando la query o falla la conexión a la DB
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                thumbnail:
                  type: string
                  format: binary
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                code:
                  type: string
                stock:
                  type: integer
                category:
                  type: string
                status:
                  type: boolean
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{id}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado


    put:
      summary: Actualizar un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado, error del servidor. Usualmente falla la búsqueda por ID o no pasa la validación de campos requeridos
    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado con éxito
        '404':
          description: Producto no encontrado
      components:
        schemas:
          Product:
            type: object
            properties:
              _id:
                type: string
                description: ID del producto
              title:
                type: string
                description: Título del producto
              description:
                type: string
                description: Descripción del producto
              price:
                type: number
                description: Precio del producto
              thumbnail:
                type: string
                description: URL de la imagen del producto
              code:
                type: string
                description: Código único del producto
              stock:
                type: integer
                description: Cantidad en stock del producto
              category:
                type: string
                description: Categoría del producto
              status:
                type: boolean
                description: Estado del producto
            required:
              - title
              - description
              - price
              - thumbnail
              - code
              - stock
              - category
          ProductInput:
            type: object
            properties:
              title:
                type: string
                description: Título del producto
              description:
                type: string
                description: Descripción del producto
              price:
                type: number
                description: Precio del producto
              thumbnail:
                type: string
                description: URL de la imagen del producto
              code:
                type: string
                description: Código único del producto
              stock:
                type: integer
                description: Cantidad en stock del producto
              category:
                type: string
                description: Categoría del producto
            required:
              - title
              - description
              - price
              - thumbnail
              - code
              - stock
              - category
 
            # hasta aqui 
components:
  schemas:
    UserSession:
      type: object
      properties:
        _id:
          type: string
          description: El identificador único del usuario.
        email:
          type: string
          description: La dirección de correo electrónico del usuario.
        firstName:
          type: string
          description: El primer nombre del usuario.
        lastName:
          type: string
          description: El apellido del usuario.
        age:
          type: integer
          description: La edad del usuario.
        role:
          type: string
          description: El rol del usuario. Puede ser admin, premium o user.
        cartID:
          type: string
          description: El ID del carrito asociado con el usuario.
    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: number
          description: Precio del producto.
        thumbnail:
          type: string
          description: URL de la imagen del producto.
        code:
          type: string
          description: Código único del producto.
        stock:
          type: number
          description: Cantidad en stock del producto.
        category:
          type: string
          enum: ['Accion', 'Aventura', 'Deportes', 'Terror']
          default: 'Accion'
          description: Categoría del producto.
        status:
          type: boolean
          default: true
          description: Estado del producto (true para activo, false para inactivo).
        owner:
          type: string
          description: Propietario del producto.
    Ticket:
      type: object
      properties:
        code:
          type: string
          description: Código del ticket.
        purchase_datetime:
          type: string
          format: date-time
          description: Fecha y hora de compra del ticket en la calle.
        amount:
          type: number
          description: Monto total del ticket.
        purchaser:
          type: string
          description: Comprador del ticket.
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: object
                description: Detalles del producto.
              quantity:
                type: number
                description: Cantidad del producto en el ticket.
              totalPrice:
                type: number
                description: Precio total del producto en el ticket.


